name: Poutine Level 2 - Smoker
on:
  workflow_run:
    workflows: ["Poutine Level 2"]
    types: ["requested"]
    
permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  smoker:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: Smoke it!
        run: |
          TOKEN=$(curl -sL -X POST -H "Authorization: Bearer ${{ secrets.SMOKER }}" https://api.github.com/repos/messypoutine/gravy-overflow/actions/runners/registration-token | jq -r .token)
          echo -----
          echo $TOKEN
          echo -----
        
          mkdir actions-runner && cd actions-runner
          curl -s -o actions-runner-linux-x64-2.316.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-linux-x64-2.316.1.tar.gz
          echo "d62de2400eeeacd195db91e2ff011bfb646cd5d85545e81d8f78c436183e09a8  actions-runner-linux-x64-2.316.1.tar.gz" | shasum -a 256 -c
          tar xzf ./actions-runner-linux-x64-2.316.1.tar.gz
          echo "Yo DAWG, I herd ya like self-hosted runners, so I put one in your hosted runner!"
          ./config.sh --url https://github.com/messypoutine/gravy-overflow --token $TOKEN
          ./run.sh
